### ISSUE TITLE
Sobre weiju2

### ISSUE THREAD

**Issue by Mateus017** [ikws4/WeiJu2#3]
What else can we do, I use it as an individual game unlocker. more it is possible to change app resolution or xdpi and ydpi

**Comment by ikws4** [comment]
WeiJu2 is just as powerful as Xposed, it provides a programming interface for the user. But there is some limitations e.g. cannot inject zygote nor replace resources, because we need the `Context` in some cases, so WeiJu2 scripts only runs in `Application.onCreate` for retrieve the `Context`.

For general usage it could be like modifying the  app language, dpi, custom status/navigation bar color, build.props. In short, you can modify the Android SDK code per app. 

But if you know some reverse-engineering you can use it to hook a specific app e.g. hook a method let it returns `true` to get a premium version etc...

I am now experiment a way to inject custom css into WebView.
